version: "3"

services:
  postgresql:
    container_name: gptnotes-postgresql
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    networks:
      - gptnotes-network
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: gptnotes-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    networks:
      - gptnotes-network
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgresql
  
  flask-app:
    container_name: gptnotes-flask-app
    image: gptnotes-flask-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: gptNotes/Dockerfile
    environment:
      SERVICE_PORT: 8081
    ports:
      - 8081:8081
    networks:
      - gptnotes-network
    depends_on:
      - postgresql

volumes:
  postgres:
  pgadmin:

networks:
  gptnotes-network:
    name: "gptnotes-network"
